/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vteba_test_NativeTest */

#ifndef _Included_com_vteba_test_NativeTest
#define _Included_com_vteba_test_NativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vteba_test_NativeTest
 * Method:    testString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_vteba_test_NativeTest_testString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_vteba_test_NativeTest
 * Method:    testByteString
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_vteba_test_NativeTest_testByteString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_vteba_test_NativeTest
 * Method:    testBytes
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_vteba_test_NativeTest_testBytes
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_vteba_test_NativeTest
 * Method:    testInteger
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_vteba_test_NativeTest_testInteger
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
